debug: false

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
#        include: '*'
        include: health, info, metrics, prometheus
      cors:
        allowed-origins: "https://example.com"
        allowed-methods: GET

server:
  port: 8080
  shutdown: graceful
  servlet:
    contextPath: /dcv

logging:
  file:
    name: target/app.log
  pattern:
    level: corrId:%X{corrId} %5p
  level:
    root: INFO
    org.dcv: INFO

spring:
  lifecycle:
    timeout-per-shutdown-phase: 10s

dcv:
  keystore: src/test/resources/keystore
